import { AfterViewInit, Component, OnInit, ViewChild } from '@angular/core';
import { IReportEmbedConfiguration, models, Page, Report, service, VisualDescriptor } from 'powerbi-client';
import { PowerBIReportEmbedComponent } from 'powerbi-client-angular';

@Component({
  selector: 'app-power-bi',
  templateUrl: './power-bi.component.html',
  styleUrls: ['./power-bi.component.css']
})
export class PowerBiComponent implements OnInit {
  @ViewChild(PowerBIReportEmbedComponent) reportObj!: PowerBIReportEmbedComponent;

  reportConfig: IReportEmbedConfiguration = {
    type: 'report',
    embedUrl: undefined,
    tokenType: models.TokenType.Embed,
    accessToken: undefined,
    settings: undefined,
  };

  id = '45716bdf-01f6-4d12-866c-a3eb1010f253';
  token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJodHRwczovL2FuYWx5c2lzLndpbmRvd3MubmV0L3Bvd2VyYmkvYXBpIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvYmMwYzBlYTAtOWRmZi00MDg1LWJlODgtMGNmMGFhNzkxNDFlLyIsImlhdCI6MTY1OTA5NzcxNiwibmJmIjoxNjU5MDk3NzE2LCJleHAiOjE2NTkxMDIwMzYsImFjY3QiOjAsImFjciI6IjEiLCJhaW8iOiJBU1FBMi84VEFBQUFwcVVlWWFRN0pzYnJ6NkYxb3lHdnMvM25HSktHb05KTCtweHpZbVZhRVQwPSIsImFtciI6WyJwd2QiXSwiYXBwaWQiOiI0YzU1NTA1Ni0zMzZmLTQ2MzAtYWRjMC1kODk4YWUwMWI1OTkiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IlJ1aXogVXJyZWEiLCJnaXZlbl9uYW1lIjoiT3NjYXIgRGFuaWVsIiwiaXBhZGRyIjoiMTgxLjQ5LjIwMS44OCIsIm5hbWUiOiJPc2NhciBEYW5pZWwgUnVpeiBVcnJlYSIsIm9pZCI6IjBiMGVlMjJhLWZiMjUtNGI0MS1hMDFhLTUzNDVjODU0NjI2YyIsInB1aWQiOiIxMDAzMjAwMjA0NzFBODc3IiwicmgiOiIwLkFTWUFvQTRNdlAtZGhVQy1pQXp3cW5rVUhna0FBQUFBQUFBQXdBQUFBQUFBQUFBbUFGcy4iLCJzY3AiOiJBcHAuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZC5BbGwgQ2FwYWNpdHkuUmVhZFdyaXRlLkFsbCBDb250ZW50LkNyZWF0ZSBEYXNoYm9hcmQuUmVhZC5BbGwgRGFzaGJvYXJkLlJlYWRXcml0ZS5BbGwgRGF0YWZsb3cuUmVhZC5BbGwgRGF0YWZsb3cuUmVhZFdyaXRlLkFsbCBEYXRhc2V0LlJlYWQuQWxsIERhdGFzZXQuUmVhZFdyaXRlLkFsbCBHYXRld2F5LlJlYWQuQWxsIEdhdGV3YXkuUmVhZFdyaXRlLkFsbCBSZXBvcnQuUmVhZC5BbGwgUmVwb3J0LlJlYWRXcml0ZS5BbGwgU3RvcmFnZUFjY291bnQuUmVhZC5BbGwgU3RvcmFnZUFjY291bnQuUmVhZFdyaXRlLkFsbCBXb3Jrc3BhY2UuUmVhZC5BbGwgV29ya3NwYWNlLlJlYWRXcml0ZS5BbGwiLCJzdWIiOiJEaDJiRGJKS01ZTFdPMzVXUTctdzIzRElvREk2RXJrN0s2aFdxSG9qM0RnIiwidGlkIjoiYmMwYzBlYTAtOWRmZi00MDg1LWJlODgtMGNmMGFhNzkxNDFlIiwidW5pcXVlX25hbWUiOiJkZXNhcnJvbGxhZG9yLml0czRAbWV0Z3JvdXBzYXMuY29tIiwidXBuIjoiZGVzYXJyb2xsYWRvci5pdHM0QG1ldGdyb3Vwc2FzLmNvbSIsInV0aSI6IkRyQkQ3Nm5aSTA2YXI3YnV3VTRpQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdfQ.iFS-jgkd9iectQes21YDihuUbalfAz6gDXb5rivhsFO4MMJkWFGfnrYTJDOq5BcmyYUFkzgNKKHOjNRBY-HnbFkQ2hgVQ9v89rICyd7lPJp6spQqxuIR0wxC0W0gV7zpZ5Vcq0eP2oawiMBHPKcCPmCfbSM37orBp5P6bppp9Y_905Y0FfOcB-aeJrcyxLZjiHHiXiVxdshMvyYyx_is9BGlXADOD6kOnjbP5eb7B3Nih26Qp7YlfoQq_S-vycGD5V__FjR_67uZhshZwVi0c5W86roU8nmyadJacEOdYU4fXOgt1_arwlZL8Hb7FxRSvLXRMmeP2-5__F4XkiDviQ';
  embedUrl = 'https://app.powerbi.com/reportEmbed?reportId=45716bdf-01f6-4d12-866c-a3eb1010f253&config=eyJjbHVzdGVyVXJsIjoiaHR0cHM6Ly9XQUJJLVBBQVMtMS1TQ1VTLXJlZGlyZWN0LmFuYWx5c2lzLndpbmRvd3MubmV0IiwiZW1iZWRGZWF0dXJlcyI6eyJtb2Rlcm5FbWJlZCI6dHJ1ZSwiYW5ndWxhck9ubHlSZXBvcnRFbWJlZCI6dHJ1ZSwiY2VydGlmaWVkVGVsZW1ldHJ5RW1iZWQiOnRydWUsInVzYWdlTWV0cmljc1ZOZXh0Ijp0cnVlLCJza2lwWm9uZVBhdGNoIjp0cnVlfX0%3d';



  constructor() { }

  ngOnInit(): void {
    this.reportConfig = {
      ...this.reportConfig,
      id: this.id,
      embedUrl: this.embedUrl,
      accessToken: this.token,
    }
  }
}
export interface ConfigResponse {
  Id: string;
  EmbedUrl: string;
  EmbedToken: {
    Token: string;
  };
}

